name: json_stream_parser
description:
    A JSON parser that's capable of handling streams of characters.
    It doesn't depend on dart:io or dart:html so it can be used
    either in the client- or server- side.
version: 0.2.1
author: Adam Stark <llamadonica@gmail.com>
homepage: https://github.com/llamadonica/dart-json-stream-parser

environment:
  sdk: '>=1.11.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
