name: json_stream_parser
description:
    A JSON parser that's capable of handling streams of characters.
    It doesn't depend on dart:io or dart:html so it can be used
    either in the client- or server- side.
version: 2.0.2
author: Adam Stark <llamadonica@gmail.com>
homepage: https://github.com/llamadonica/dart-json-stream-parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: '^3.0.1'

dev_dependencies:
  test: '^1.16.0'